application: idealizer1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /s
  static_dir: s

- url: /.*
  script: idealizer.application

libraries:
- name: jinja2
  version: latest